### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../data/codes/pca_True_6v.npz'

### ISSUE THREAD

**Issue by tylee0325** [cianeastwood/qedr#4]
Hi, Thank you for the great repository. 
I also read your paper very interestingly. 

I tried to reproduce your result, but I couldn't because of such an error. 

FileNotFoundError: [Errno 2] No such file or directory: '../../data/codes/pca_True_6v.npz'

I downloaded the data set, but I couldn't find this. 
How can I get this dataset? 

Thank you in advance :)

**Comment by cianeastwood** [comment]
To get the PCA "codes", you must first run the PCA "model", i.e. python main.py from ../qedr/models/pca/

**Comment by tylee0325** [comment]
that error occurs when I try to run models/pca/main.py
Did I something wrong ? :(

**Comment by cianeastwood** [comment]
Looks like you need to sort out your PYTHONPATH. That's an error when saving, not loading. Try PYTHONPATH=[/path/to/qedr/] python main.py, as in readme
