### ISSUE TITLE
length of code C

### ISSUE THREAD

**Issue by betterze** [cianeastwood/qedr#5]
Dear Cian,

Thank you for your great implement. I just want to make sure i use this metric correctly. 

Dose the dimention D of code C (in 2 THEORETICAL FRAMEWORK of the paper) affect the output number? If so, how it affect disentanglement, completeness and informativeness? Can I use this metric to compare two latent codes with different length?

Thank you very much for your help.

Best Wishes,

Alex

**Comment by cianeastwood** [comment]
Hi Alex,

I don't know what you mean by output number. D is the dimension of your latent code or representation, so if that's your output, then yes. The metrics can be used to compare codes of different lengths -- usually it is just the averages that are reported.

Cian

**Comment by betterze** [comment]
I understand it now. Thx
